export const colors = {
  primary: '#8B4513',
  primaryLight: '#A0522D',
  primaryDark: '#6B3410',
  secondary: '#FFD700',
  secondaryLight: '#FFE44D',
  background: '#FFF8F0',
  surface: '#FFFFFF',
  surfaceVariant: '#F5F0EB',
  text: '#2D1810',
  textSecondary: '#8B7355',
  textLight: '#B8A590',
  error: '#D32F2F',
  errorLight: '#FFCDD2',
  success: '#388E3C',
  successLight: '#C8E6C9',
  warning: '#F57C00',
  warningLight: '#FFE0B2',
  accent: '#D2691E',
  accentLight: '#E8915A',
  border: '#E0D5C8',
  divider: '#F0E8DE',
  overlay: 'rgba(45, 24, 16, 0.5)',
  white: '#FFFFFF',
  black: '#000000',
  transparent: 'transparent',
  star: '#FFD700',
  instagram: '#E4405F',
  google: '#4285F4',
  whatsapp: '#25D366',
  facebook: '#1877F2',
} as const;

export type ColorKey = keyof typeof colors;

// React Native Paper compatible theme
export const theme = {
  colors: {
    primary: colors.primary,
    primaryContainer: colors.primaryLight,
    secondary: colors.secondary,
    secondaryContainer: colors.secondaryLight,
    background: colors.background,
    surface: colors.surface,
    surfaceVariant: colors.surfaceVariant,
    error: colors.error,
    errorContainer: colors.errorLight,
    onPrimary: colors.white,
    onSecondary: colors.black,
    onBackground: colors.text,
    onSurface: colors.text,
    onError: colors.white,
    outline: colors.border,
    elevation: {
      level0: 'transparent',
      level1: colors.surfaceVariant,
      level2: '#F0EBE5',
      level3: '#EBE5DE',
      level4: '#E8E0D8',
      level5: '#E3DAD0',
    },
  },
};
